apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    repoURL: http://gitlab-webservice-default.gitlab.svc:8181/root/iot.git
    path: .
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
