#!/bin/bash
# Set default values
CLUSTER_NAME=mycluster
DOMAINE=k3d.argocd.com
WAIT_TIMEOUT=600s
idx=0

# Function to print a message with the index number
print_msg() {
    idx=$((idx+1))
    echo -e "\033[32m[$idx] $1\033[0m"
}

# Function to check if a command exists and install it if necessary
check_command() {
  for command in "$@"; do
    if ! [ -x "$(command -v $command)" ]; then
      print_msg "Installing $command"
      case $command in
        docker)
           apt-get remove docker docker-engine docker.io containerd runc
           apt-get -y update
           apt-get -y install \
            ca-certificates \
            curl \
            gnupg
           install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg |  gpg --dearmor -o /etc/apt/keyrings/docker.gpg
           chmod a+r /etc/apt/keyrings/docker.gpg
          echo \
              "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
              "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
           tee /etc/apt/sources.list.d/docker.list > /dev/null
           apt-get -y update
           apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          ;;
        k3d)
          wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          ;;
        kubectl)
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
          # Output must be "kubectl: Ok"
           install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          rm -f kubectl kubectl.sha256
          ;;
      esac
    fi
  done
}

install_metalLB(){
  print_msg "Install metallb"
  sudo kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.3/config/manifests/metallb-native.yaml
  print_msg "Waiting metallb"
  sleep 10
  sudo kubectl wait --for=condition=Ready pods --all -n metallb-system 
  print_msg "Apply ConfigMap"
  sudo kubectl apply -f ../ConfigMap/. 
}

# Function to delete the cluster and namespaces
delete_cluster() {
  print_msg "Deleting namespaces"
  sudo kubectl delete namespace argocd dev --ignore-not-found=true
  print_msg "Deleting cluster"
  sudo k3d cluster delete $CLUSTER_NAME
}

# Function to create the cluster and deploy ArgoCD and the app
# # Function to create the cluster and deploy ArgoCD and the app
install_argo() {
  print_msg "Creating cluster"
  sudo k3d cluster create $CLUSTER_NAME --wait --timeout 120s

  print_msg "Creating namespaces"
  sudo kubectl create namespace argocd
  sudo kubectl create namespace dev
  install_metalLB

  print_msg "Deploying ArgoCD"
  sudo kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  print_msg "Waiting ArgoCD"
  sudo kubectl wait --timeout $WAIT_TIMEOUT --for=condition=Ready pods --all -n argocd
  print_msg "Patch ArgoCD to LoadBalancer"
  sudo kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer", "loadBalancerIP": "172.18.0.10"}}'

  print_msg "Deploying app"
  sudo kubectl apply -f ./config/configs.yml
  print_msg "Waiting app"
  sudo kubectl wait --timeout $WAIT_TIMEOUT --for=condition=Ready pods --all -n argocd
  print_msg "Getting admin password"
  password=""
  while [ -z "$password" ]; do
      password=$(sudo kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d)
      
      if [ -z "$password" ]; then
          echo "Error: get password. try again in few second..."
          sleep 5
      fi
  done
  IP=$(sudo kubectl get svc -n argocd | grep LoadBalancer | awk '{ print $4}')
  echo "ArgoCD: https://${DOMAINE} || https://${IP}"
  printf "\n\n\tadmin\n\t%s\n" "$password"
}

check_command docker k3d kubectl
delete_cluster
install_argo
echo "deploy done!!\nFor start ArgoCD: install start"
