#!/bin/bash
#
DOMAIN="k3d.gitlab.com"

# Function to print a message with the index number
print_msg() {
    export IDX=$(expr $IDX + 1)
    echo -e "\033[32m[$IDX] $1\033[0m"
}

update_helm(){
  print_msg "Install heml"
  helm repo add gitlab https://charts.gitlab.io/
  helm repo update
}


install_gitlab(){
  update_helm
  print_msg "Create namespace"
  sudo kubectl create namespace gitlab
  print_msg "Install gitlab"
  sudo helm upgrade --install gitlab gitlab/gitlab \
      -n gitlab \
      -f https://gitlab.com/gitlab-org/charts/gitlab/raw/master/examples/values-minikube-minimum.yaml \
      --set global.hosts.domain=${DOMAIN} \
      --set global.hosts.https=false \
      --set global.edition=ce \
      --set runners.install=false \
      --timeout 600s
  print_msg "Wait service running"
  sudo kubectl wait --for=condition=ready --timeout=1200s pod -l app=webservice -n gitlab
  print_msg "Apply ingress controller"
  sudo kubectl apply -f ./ingress/ingress-gitlab.yaml
  sleep 10
  PASS=$(sudo kubectl get secret gitlab-gitlab-initial-root-password -n gitlab -ojsonpath='{.data.password}' | base64 --decode)
  IP=$(sudo kubectl get svc -n argocd | grep LoadBalancer | awk '{ print $4}')
  echo ""
  echo "-----------------------------------------------------------------------------"
  echo "gitlab: https://${DOMAIN}"
  printf "\ntroot\n\t%s\n" "$PASS"
  printf "Dont forget to add to your /etc/hosts:\n ${IP} ${DOMAIN}\n"
  echo "-----------------------------------------------------------------------------"
  echo ""
}

install_gitlab
